// Mocks generated by Mockito 5.0.3 from annotations
// in guitardiary/test/data/repositories/guitar_dates_repository_test.dart.
// Do not manually edit this file.

import 'package:guitardiary/data/services/sqlite_database_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i2.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }
}
